# Generated by Django 5.0.6 on 2024-05-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='regdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='board',
            name='writer',
            field=models.CharField(max_length=30),
        ),
    ]
